### ISSUE TITLE
🐞Docker trade error

### ISSUE THREAD

**Issue by ghost** [Rikj000/MoniGoMani#152] opened 2021-10-07 11:59 UTC
Hello,
When I start hyperopt-trade or backtesting, I get the following error. I pulled the files from the site and installed using docker-compose pull. I'm waiting for your help. Thanks in advance!

2021-10-07 11:54:16,752 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 48, in start_backtesting
    config = setup_optimize_configuration(args, RunMode.BACKTEST)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 21, in setup_optimize_configuration
    config = setup_utils_configuration(args, method)
  File "/freqtrade/freqtrade/configuration/config_setup.py", line 21, in setup_utils_configuration
    config = configuration.get_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 111, in load_config
    self._process_optimize_options(config)
  File "/freqtrade/freqtrade/configuration/configuration.py", line 261, in _process_optimize_options
    self._process_datadir_options(config)
  File "/freqtrade/freqtrade/configuration/configuration.py", line 199, in _process_datadir_options
    config.update({'datadir': create_datadir(config, self.args.get('datadir', None))})
  File "/freqtrade/freqtrade/configuration/directory_operations.py", line 18, in create_datadir
    exchange_name = config.get('exchange', {}).get('name').lower()
AttributeError: 'NoneType' object has no attribute 'lower'

my command is = docker-compose run freqtrade backtesting --config /freqtrade/user_data/mgm-config.example.json --strategy MoniGoManiHyperStrategy

**Comment by Rikj000** [comment] 2021-10-07 12:12
Duplicate of https://github.com/Rikj000/MoniGoMani/issues/148
[Check reply there](https://github.com/Rikj000/MoniGoMani/issues/148#issuecomment-937024631)

**Closed as completed by Rikj000** 2021-10-07 12:12 UTC
Labels: Won't Fix
