### ISSUE TITLE
🐞 Fix bugs introduced by updating Freqtrade

### ISSUE THREAD

**Issue by rodrigogs** [Rikj000/MoniGoMani#91] opened 2021-07-13 14:57 UTC
I just updated my freqtrade image, and now I get this message when I try to hyperopt:

`freqtrade - ERROR - This strategy requires 4800 candles to start. Binance only provides 1000 for 5m.`

Any idea why?

**Comment by Rikj000** [comment] 2021-07-13 16:44
> `freqtrade - ERROR - This strategy requires 4800 candles to start. Binance only provides 1000 for 5m.` 
> Any idea why?

Yes, you are on the wrong Freqtrade commit, you currently need an older version of Freqtrade, 
as mentioned lately on [the front page of the development branch](https://github.com/Rikj000/MoniGoMani/blob/development/README.md).


It appears TimeFrame-Zoom got broken on newer Freqtrade versions.
It always zooms in now, even when dry/live running, which is not as intended + causing your issues.

This was also mentioned earlier today in the [help channel on Discord](https://discord.com/channels/819237123009150977/829415367713095710/864443224381718561).

You'll have to wait till I or another willing developer update Freqtrade again and then iron out all the bugs introduced into MGM by doing that.
On my en this will probably happen:
- Right before wrapping up the [next MGM release](https://github.com/Rikj000/MoniGoMani/milestone/2)
- Could also happen earlier if I want/need a specific & very recently added feature out of Freqtrade for MGM

**Comment by rodrigogs** [comment] 2021-07-13 19:08
Oh, I didn't notice your note in the readme. Thank you, a fast and precise answer as always :)

**Comment by topscoder** [comment] 2021-07-20 19:20
Took a while, but figured out this is the particular commit in freqtrade/freqtrade who is responsible for this issue:

https://github.com/freqtrade/freqtrade/commit/2f33b97b95c62ab0fec089098a6cf1eeae01d041

**Comment by Rikj000** [comment] 2021-07-20 19:38
> [freqtrade/freqtrade@2f33b97](https://github.com/freqtrade/freqtrade/commit/2f33b97b95c62ab0fec089098a6cf1eeae01d041)

Good job mate! :mechanical_arm: Hmmm this is problematic though... :thinking:
The [validate_required_startup_candles()](https://github.com/freqtrade/freqtrade/blob/f870c0099b0de72a18e6f396e63e8f0e8da735a6/freqtrade/exchange/exchange.py#L457) function indeed seems to be the issue here :eyes:
However we cannot modify the execution of this function from at the strategy level I fear..
I believe a PR to Freqtrade will be needed to resolve this and to allow us to keep using TimeFrame-Zoom.. :thinking:

Because it's ok for Freqtrade to throw this error when you're Dry/Live running, because Binance simply will not allow you to use that many candles during dry/live runs.
But during backtesting/hyperopting this is no issue, because we already downloaded all the candle data prior to our backtesting/hyperopting, so we will not run into Binance API issues.

**Comment by topscoder** [comment] 2021-07-20 19:42
I've hacked a bit around and it seems the startup_candle_count (2400) during hyperopting isn't accepted anymore. But, the default (400) is. 

So I've added a check to only change the startup_candle_count in backtest-mode.

```python
MasterMoniGoManiHyperStrategy.py

358: -            self.startup_candle_count *= self.timeframe_multiplier

358: +            if RunMode(config.get('runmode', RunMode.OTHER)) is RunMode.BACKTEST:
358: +                self.startup_candle_count *= self.timeframe_multiplier
```

**Comment by Rikj000** [comment] 2021-07-20 19:43
> I've hacked a bit around and it seems the startup_candle_count (2400) during hyperopting isn't accepted anymore. But, the default (400) is.

Yes exactly what I meant! :clap: Would you be up for it to describe this issue in a PR to Freqtrade?

**Comment by topscoder** [comment] 2021-07-20 19:45
> > I've hacked a bit around and it seems the startup_candle_count (2400) during hyperopting isn't accepted anymore. But, the default (400) is.
> 
> Yes exactly what I meant! 👏 Would you be up for it to describe this issue in a PR to Freqtrade?

Uhmm, I think so... But my proposal above is an easy patch inside `MasterMoniGoManiHyperStrategy.py`. That would cost a lot less effort if I'm guessing right?

**Comment by topscoder** [comment] 2021-07-20 19:47
I'll create a PR containing above patch to close this issue. We can discuss it easier if it's needed.

**Comment by Rikj000** [comment] 2021-07-20 19:51
> Uhmm, I think so... But my proposal above is an easy patch inside `MasterMoniGoManiHyperStrategy.py`. That would cost a lot less effort if I'm guessing right?

Oh damn I didn't notice! Thought you modified Freqtrades source code :open_mouth:

**Comment by Rikj000** [comment] 2021-07-20 19:55
> ```python
> MasterMoniGoManiHyperStrategy.py
> 
> 358: -            self.startup_candle_count *= self.timeframe_multiplier
> 
> 358: +            if RunMode(config.get('runmode', RunMode.OTHER)) is RunMode.BACKTEST:
> 359: +                self.startup_candle_count *= self.timeframe_multiplier
> ```

What is the startup candle count that get's printed to the console with this patch? :thinking:
If it gets rid of the bug I believe it will be the "unzoomed" 400 candle startup count that is used?

**Comment by topscoder** [comment] 2021-07-20 19:58
Correct. 400

**Comment by Rikj000** [comment] 2021-07-20 20:50
> Correct. 400

Now that I think more about it, I believe we don't **need** the multiplier on the `startup_candle_count`.. :thinking:

I found the commit where it got pushed https://github.com/Rikj000/MoniGoMani/commit/41f987543cb689d045d27d2af456c184f8eb230e 
There `MoniGoManiHyperStrategy.py` file, Line 916: `self.startup_candle_count *= self.timeframe_multiplier` was added.

I also found [HyperOptResults5_Pt1-23-05-2021_MoniGoManiConfiguration_bugfixed_startup_candle_count.log](https://github.com/Rikj000/MoniGoMani/blob/main/Some%20Test%20Results/v0.11.0/HyperOptResults5_Pt1-23-05-2021_MoniGoManiConfiguration_bugfixed_startup_candle_count.log) in the `Some Test Results/v0.11.0` folder. And I now recall that it was not really an issue back then, but something I believed what was needed for the timeframe zoom implementation to work correctly.

Back then, I thought, if the timeframe zooms in to 5 minutes, then the dataframe timerange will be too short for the larger informative indicators/signals that get added in the dataframe *(Because 400\*5m startup is shorter then 400\*30m startup)*.

However, if we follow the [get_pair_dataframe()](https://github.com/Rikj000/MoniGoMani/blob/50fc28d1b79e885ff50df1d11f87078779925f49/user_data/strategies/MasterMoniGoManiHyperStrategy.py#L336) function in `MasterMoniGoManiHyperStrategy.py`, then we end up at Freqtrade's [load_pair_history()](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/data/history/history_utils.py#L23) function, which takes in the `startup_candles` parameter.

2 things to consider here:
- No matter if under 5m candles or under 30m or any other candles, the 200EMA (which has the longest startup of the signals used by MGM), will always only need 400 candles as it's startup count.
- We are never interested in the indicator/signal data of the `backtest_timeframe`, only in it's intra-candle price movement

After my re-reflection on it, I believe this line (`self.startup_candle_count *= self.timeframe_multiplier`) as a whole can be removed safely as the proper fix! :tada:

**Comment by hoanghnbk** [comment] 2021-07-25 20:09
@rodrigogs in case you're using docker, I created an image that use freqtrade commit `3503fdb4`  as mentioned in [Discord](https://discord.com/channels/819237123009150977/825737481856221224/860803841590165504). so you only need to change in docker-compose file : from `image: freqtradeorg/freqtrade:develop` to `hoanghnbk/freqtrade_3503fdb4` and it will work

**Comment by rodrigogs** [comment] 2021-07-25 21:01
I already did the same thing hahaha

Thanks!

**Comment by Rikj000** [comment] 2021-08-14 13:32
Even though PR https://github.com/Rikj000/MoniGoMani/pull/99 got merged I truly recommend to **not** update your Freqtrade!

Please remain on Freqtrade commit https://github.com/freqtrade/freqtrade/pull/5219/commits/3503fdb4ec31be99f433fdce039543e0911964d6 until instructed otherwise!

**Only update** your Freqtrade if you wish to:
- Check for new breakage in MGM that might occur
- BugFix & PR new breakage if it occurs

**Comment by edebie** [comment] 2021-08-23 09:45
> @rodrigogs in case you're using docker, I created an image that use freqtrade commit `3503fdb4` as mentioned in [Discord](https://discord.com/channels/819237123009150977/825737481856221224/860803841590165504). so you only need to change in docker-compose file : from `image: freqtradeorg/freqtrade:develop` to `hoanghnbk/freqtrade_3503fdb4` and it will work

You also need to update docker/Dockerfile.MoniGoMani

**Comment by Rikj000** [comment] 2021-09-13 10:41
:ballot_box_with_check: Handle Freqtrade's new way of dealing with protections, appears like they aren't used in the `.json` files anymore

**Comment by Rikj000** [comment] 2022-01-16 16:15
Updated to `freqtrade-2021.11` in: https://github.com/Rikj000/MoniGoMani/compare/527b1061cd00...fdbb52657fb4 :tada:

**Closed by Rikj000** 2022-01-16 16:15 UTC
Labels: Bug - Fix Needed, In Progress
