### ISSUE TITLE
🐞 Fresh Install on WSL - CRITICAL - [Errno 2] No such file or directory during `Copy MoniGoMani to the monigomani folder in the target directory and symbolic linking files`

### ISSUE THREAD

**Issue by briankudera** [Rikj000/MoniGoMani#170] opened 2021-10-23 06:10 UTC
1. All requirements check passed at start of install.
2. I've switched sh to use bash.
3. Running as root to try and eliminate any permissions errors.
4. End of install output is below.
5. I've cleared the directory and tried install 3 times but the same error persists.

I've confirmed that this file does exist:

- /mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/user_data/hyperopts/MGM_SortinoHyperOptLoss.py

And this folder does exist:

- /mnt/c/Users/brian/Documents/freqtrade-mgm/user_data/hyperopts/MGM_SortinoHyperOptLoss.py

If I try to reinstall freqtrade and mgm both one at a time, I get permissions errors on both.

```
You can see the list of available bot sub-commands by executing 'source .env/bin/activate; freqtrade --help'.
You verify that freqtrade is installed successfully by running 'source .env/bin/activate; freqtrade --version'.
INFO - Removing UI directory content.
INFO - Downloading https://github.com/freqtrade/frequi/releases/download/0.1.6/freqUI.zip
INFO - ✔ Successfully installed FreqUI!
✔ Freqtrade setup completed!
INFO - 🍺 Freqtrade has been installed. You can now proceed to install MoniGoMani. (Hint: mgm-hurry install_mgm)
INFO - 💨 💨 💨
       👉 Install MoniGoMani
       💨 💨 💨
🤷 No "mgm-config.json" file found.
WARNING - 🤷 No "mgm-config.json" file found.
✔ 👉  Clone MoniGoMani repository on the latest commit
⠙ 👉  Copy MoniGoMani to the monigomani folder in the target directory and symbolic linking files**CRITICAL - [Errno 2] No such file or directory**: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/user_data/hyperopts/MGM_SortinoHyperOptLoss.py' -> '/mnt/c/Users/brian/Documents/freqtrade-mgm/user_data/hyperopts/MGM_SortinoHyperOptLoss.py'
😕 MoniGoMani installation failed


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  🎉  You are all set! We hope you enjoy your ride.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani#
```

**Trying to install freqtrade on its own:**
```root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm# ./monigomani/mgm-hurry install_freqtrade
                                     _
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/

INFO - 💨 💨 💨
       👉 Install Freqtrade
       💨 💨 💨
? It looks like Freqtrade is already installed. Proceed to overwrite? Yes
✔ 👉  Clone Freqtrade repository and resetting to commit 3503fdb4ec31be99f433fdce039543e0911964d6
Traceback (most recent call last):
  File "./monigomani/mgm-hurry", line 1150, in <module>
    fire.Fire(MGMHurry)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./monigomani/mgm-hurry", line 251, in install_freqtrade
    self.freqtrade_cli.download_setup_freqtrade(target_dir=target_dir, branch=branch,
  File "/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 190, in download_setup_freqtrade
    self.copy_installation_files(temp_dirname, target_dir)
  File "/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 217, in copy_installation_files
    copytree(temp_dirname, target_dir, dirs_exist_ok=True)
  File "/usr/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/tmp6f4mrrl2/.git/objects/pack/pack-fa764bcbf6c42f34442191631f2339c6d03a4b47.pack', '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/.git/objects/pack/pack-fa764bcbf6c42f34442191631f2339c6d03a4b47.pack', "[Errno 13] Permission denied: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/.git/objects/pack/pack-fa764bcbf6c42f34442191631f2339c6d03a4b47.pack'"), ('/tmp/tmp6f4mrrl2/.git/objects/pack/pack-fa764bcbf6c42f34442191631f2339c6d03a4b47.idx', '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/.git/objects/pack/pack-fa764bcbf6c42f34442191631f2339c6d03a4b47.idx', "[Errno 13] Permission denied: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/.git/objects/pack/pack-fa764bcbf6c42f34442191631f2339c6d03a4b47.idx'")]
root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm#
```

**Trying to install mgm on its own:**
```root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm# python3 mgm-hurry install_mgm
                                     _
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/

INFO - 💨 💨 💨
       👉 Install MoniGoMani
       💨 💨 💨
🤷 No "mgm-config.json" file found.
WARNING - 🤷 No "mgm-config.json" file found.
✔ 👉  Clone MoniGoMani repository on the latest commit
⠏ 👉  Copy MoniGoMani to the monigomani folder in the target directory and symbolic linking filesCRITICAL - [('/tmp/tmp7v6o9tll/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.pack', '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.pack', "[Errno 13] Permission denied: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.pack'"), ('/tmp/tmp7v6o9tll/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.idx', '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.idx', "[Errno 13] Permission denied: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.idx'")]
😕 MoniGoMani installation failed
root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm# 😕 MoniGoMani installation failed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  🎉  You are all set! We hope you enjoy your ride.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani#
```

**I ran this in the freqtrade-mgm directory**
```
sudo chown -R myusername. .
```

The resulting error was a bit different, but the 2nd path it's copying to is an invalid path:
```root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm# ./monigomani/mgm-hurry install_mgm
                                     _
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _ 
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/ 

INFO - 💨 💨 💨
       👉 Install MoniGoMani
       💨 💨 💨
🤷 No "mgm-config.json" file found.
WARNING - 🤷 No "mgm-config.json" file found.
✔ 👉  Clone MoniGoMani repository on the latest commit
⠸ 👉  Copy MoniGoMani to the monigomani folder in the target directory and symbolic linking filesCRITICAL - [('/tmp/tmp41fbqp33/.git/objects/pack/pack-edefec35a83e8a09760c5d71cfd775ea243c1835.idx', '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-edefec35a83e8a09760c5d71cfd775ea243c1835.idx', "[Errno 13] Permission denied: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-edefec35a83e8a09760c5d71cfd775ea243c1835.idx'"), ('/tmp/tmp41fbqp33/.git/objects/pack/pack-edefec35a83e8a09760c5d71cfd775ea243c1835.pack', '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-edefec35a83e8a09760c5d71cfd775ea243c1835.pack', "[Errno 13] Permission denied: '/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm/monigomani/.git/objects/pack/pack-edefec35a83e8a09760c5d71cfd775ea243c1835.pack'")]
😕 MoniGoMani installation failed
root@TABLET-J4QR80FO:/mnt/c/Users/brian/Documents/monigomani/freqtrade-mgm# ```

**Comment by Rikj000** [comment] 2021-10-24 03:13
Nice catch @briankudera, I've been able to reproduce this issue on my Ubuntu WSL. 
I'm sorry for your inconvenience, but grateful for reporting this issue!

A critical permission error happens during the Ubuntu WSL installation:
```python
[
    (
        '/tmp/tmpe74xxfnk/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.pack', 
        '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.pack', 
        "[Errno 13] Permission denied: '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.pack'"
    ), 
    (
        '/tmp/tmpe74xxfnk/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.idx', 
        '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.idx', 
        "[Errno 13] Permission denied: '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-36867d179f5452188d8a2b739f7d82aaa0f50adf.idx'"
    )
]
```

Due to the permission error it fails to copy the `.pack` & `.idx` files from it's temp directory after downloading to the effective installation directory. Which leads to the installation aborting, which then gives the user a half finished installation as a result.

**Full installation log:**
[Ubuntu-WSL-Failed-Installation.log](https://github.com/Rikj000/MoniGoMani/files/7404004/Ubuntu-WSL-Failed-Installation.log)

**Comment by Rikj000** [comment] 2021-10-24 03:54
I can happily confirm that simply running the initial installer as `sudo` resolves the issue! 🎉
```powershell
/usr/bin/env sh <(sudo curl -s "https://raw.githubusercontent.com/Rikj000/MoniGoMani/development/installer.sh")
```

**Full installation log:**
[Ubuntu-WSL-Sudo-Successful-Installation.log](https://github.com/Rikj000/MoniGoMani/files/7404037/Ubuntu-WSL-Sudo-Successful-Installation.log)

I still need to test if `mgm-hurry install_freqtrade` & `mgm-hurry install_mgm` will still independently need `sudo` on Ubuntu WSL

**Comment by Rikj000** [comment] 2021-10-24 04:10
The separate update commands however will require some code changes.
Since it will get stuck on the same issue as before without `sudo`:
```log
python3 ./mgm-hurry install_mgm
===============================
                                     _
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/

INFO - 💨 💨 💨
       👉 Install MoniGoMani
       💨 💨 💨
✔ MoniGoManiHyperStrategy and configuration found
? It looks like MoniGoMani is already installed. Proceed to overwrite? Yes
? Should I print your "mgm-config-private.json" contents so you can copy it over to new installation? No
✔ 👉  Clone MoniGoMani repository on the latest commit
⠋ 👉  Copy MoniGoMani to the monigomani folder in the target directory and symbolic linking filesCRITICAL - [('/tmp/tmpy3nq7vev/.git/objects/pack/pack-0d55d73b72369ae4a085342d50eb079a9554c68a.idx', '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-0d55d73b72369ae4a085342d50eb079a9554c68a.idx', "[Errno 13] Permission denied: '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-0d55d73b72369ae4a085342d50eb079a9554c68a.idx'"), ('/tmp/tmpy3nq7vev/.git/objects/pack/pack-0d55d73b72369ae4a085342d50eb079a9554c68a.pack', '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-0d55d73b72369ae4a085342d50eb079a9554c68a.pack', "[Errno 13] Permission denied: '/mnt/c/Users/Rik/Desktop/freqtrade-mgm/monigomani/.git/objects/pack/pack-0d55d73b72369ae4a085342d50eb079a9554c68a.pack'")]
😕 MoniGoMani installation failed
```
And with `sudo` the python dependency packages for `mgm-hurry` won't be available:
```log
sudo python3 ./mgm-hurry install_mgm
====================================
[sudo] password for rikj000:
Traceback (most recent call last):
  File "./mgm-hurry", line 27, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
```

@briankudera, you should be fine if you just use the `sudo` command fix described in my previous message for now.
But to update you will need to do clean installs & then move your config files from the previous install location until I write a proper fix for this.

The issue can likely properly be resolved by using `os.chmod(path_to_file_in_temp_dir, 0o444)` on all `.pack` & `.idx` files present in the `.git/objects/pack/` folders inside the temp directories.

**Comment by Rikj000** [comment] 2021-10-24 08:38
Bug fixed in commit: https://github.com/Rikj000/MoniGoMani/commit/22c012805a3da0d43348d62d49b13eec4b860670

**Closed as completed** 2021-10-24 08:38 UTC
Labels: Bug - Fixed
