### ISSUE TITLE
`expect` failures using `installer.sh` on Ubuntu

### ISSUE THREAD

**Issue by topscoder** [Rikj000/MoniGoMani#112] opened 2021-08-23 11:29 UTC
```
 👉  Are you ready to proceed? (y/n)

  y
/dev/fd/63: 214: [: 0: unexpected operator
...
...
...
✔ 👉  Clone Freqtrade repository and resetting to commit 3503fdb4ec31be99f433fdce039543e0911964d6
✔ 👉  Copy Freqtrade installation
👉  Run Freqtrade setup
spawn ./setup.sh --install
Please deactivate your virtual environment before running setup.sh.
You can do this by running 'deactivate'.
expect: spawn id exp4 not open
    while executing
"expect "*Do you want to install dependencies for dev*" { send -- "y\r" }"
    (file "/root/freqtrade-mgm/setup.exp" line 17)
✔ Freqtrade setup completed 
```

**Comment by nuaimat** [comment] 2021-08-24 04:56
I couldn't reproduce this.  i am running ubuntu 21.10

i installed "expect" using:
`apt-get install expect` 
before starting the installer.sh 

```
./installer.sh

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ⛱️  Welcome aboard! Let's get started ...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  🚦  Requirements check
  ======================

  ✅  Python3 is installed.
  ✅  Pip3 is installed.
  ✅  Git is installed.
  ✅  cURL is installed.
  ✅  Expect is installed.
  ✅  TA-Lib (C dependency package) is installed.

  👉  Are you ready to proceed? (y/n)

  y


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ⚙️  Downloading required files...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cloning into '/draft/MoniGoMani/freqtrade-mgm/monigomani'...
remote: Enumerating objects: 4356, done.
remote: Counting objects: 100% (714/714), done.
remote: Compressing objects: 100% (456/456), done.
Receiving objects:  56% (2461/4356), 250.10 MiB | 2.35 MiB/s
remote: Total 4356 (delta 481), reused 443 (delta 254), pack-reused 3642
Receiving objects: 100% (4356/4356), 264.01 MiB | 2.52 MiB/s, done.
Resolving deltas: 100% (2896/2896), done.
Updating files: 100% (498/498), done.
Branch 'development' set up to track remote branch 'development' from 'origin'.
Switched to a new branch 'development'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ⚙️  Installing dependency packages...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Collecting art==5.2
  Downloading art-5.2-py2.py3-none-any.whl (571 kB)
     |████████████████████████████████| 571 kB 1.6 MB/s
Collecting cffi==1.14.6
  Downloading cffi-1.14.6-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (208 kB)
     |████████████████████████████████| 208 kB 10.0 MB/s
Collecting coloredlogs==15.0.1
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 3.6 MB/s
Collecting fire==0.4.0
  Downloading fire-0.4.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 7.2 MB/s
Collecting gitdb==4.0.7
  Downloading gitdb-4.0.7-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 3.1 MB/s
Collecting humanfriendly==9.2
  Downloading humanfriendly-9.2-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 5.9 MB/s
Collecting inquirerpy==0.2.4
  Downloading InquirerPy-0.2.4-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 7.4 MB/s
Collecting logger==1.4
  Downloading logger-1.4.tar.gz (1.2 kB)
Collecting plotly==5.2.2
  Downloading plotly-5.2.2-py2.py3-none-any.whl (21.8 MB)
     |████████████████████████████████| 21.8 MB 8.5 MB/s
Collecting prompt-toolkit==3.0.20
  Downloading prompt_toolkit-3.0.20-py3-none-any.whl (370 kB)
     |████████████████████████████████| 370 kB 1.9 MB/s
Collecting pycparser==2.20
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 6.2 MB/s
Collecting pygit2==1.6.1
  Downloading pygit2-1.6.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 6.6 MB/s
Collecting pyyaml==5.4.1
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux2014_aarch64.whl (788 kB)
     |████████████████████████████████| 788 kB 4.3 MB/s
Collecting shell-command==0.1
  Downloading shell_command-0.1.tar.gz (3.4 kB)
Collecting six==1.16.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting smmap==4.0.0
  Downloading smmap-4.0.0-py2.py3-none-any.whl (24 kB)
Collecting tenacity==8.0.1
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting termcolor==1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting wcwidth==0.2.5
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting yaspin==2.1.0
  Downloading yaspin-2.1.0-py3-none-any.whl (18 kB)
Building wheels for collected packages: fire, logger, shell-command, termcolor
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.4.0-py2.py3-none-any.whl size=115925 sha256=d2e8fe64984316d53c3f32bfa82bc0e581f58f9e0215f3c3f4dbdb8178d92e8d
  Stored in directory: /root/.cache/pip/wheels/2a/93/86/8cd17bc6c40fb605c3ac549d0b860ef7e84ee5f67bf01a3287
  Building wheel for logger (setup.py) ... done
  Created wheel for logger: filename=logger-1.4-py3-none-any.whl size=1789 sha256=a7efd8adc5b583af14f34f07cdae0575f0ad637e9f1682a4171225b6b5859b36
  Stored in directory: /root/.cache/pip/wheels/d6/2c/20/0bf3428f60a053875adaf43bee20695fff6e5d5a2cffaceaad
  Building wheel for shell-command (setup.py) ... done
  Created wheel for shell-command: filename=shell_command-0.1-py3-none-any.whl size=4067 sha256=fea36fb706265ee86d4725a2bee029e2d13f590adfb0c7baae042324826d3bc1
  Stored in directory: /root/.cache/pip/wheels/4e/05/e7/d347471b479f5e5c1e2be4e6a01914e9d652c4d0a3adadf828
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=bfc37ea50d49d5d79f4a6f4b34e5bc804d2e5ad95d80a887667962b00e61e1db
  Stored in directory: /root/.cache/pip/wheels/b6/0d/90/0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built fire logger shell-command termcolor
Installing collected packages: wcwidth, pycparser, termcolor, tenacity, smmap, six, prompt-toolkit, humanfriendly, cffi, yaspin, shell-command, pyyaml, pygit2, plotly, logger, inquirerpy, gitdb, fire, coloredlogs, art
Successfully installed art-5.2 cffi-1.14.6 coloredlogs-15.0.1 fire-0.4.0 gitdb-4.0.7 humanfriendly-9.2 inquirerpy-0.2.4 logger-1.4 plotly-5.2.2 prompt-toolkit-3.0.20 pycparser-2.20 pygit2-1.6.1 pyyaml-5.4.1 shell-command-0.1 six-1.16.0 smmap-4.0.0 tenacity-8.0.1 termcolor-1.1.0 wcwidth-0.2.5 yaspin-2.1.0
                                     _
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/

[WARNING] - : Could not find .hurry config file at /draft/MoniGoMani/freqtrade-mgm/.hurry
[INFO] - : 🍺 Configuration data written to ".hurry" file
[WARNING] - : FreqtradeCli - installation_exists() failed. Freqtrade binary not found in /draft/MoniGoMani/freqtrade-mgm/.env/bin/freqtrade.
[WARNING] - : 🤷 No Freqtrade installation found.
? 💨 Do you want to install Freqtrade? No
? 💨 Do you want to install MoniGoMani? Yes
? 💨 Do you want to configure it now? Yes
? 💨 Do you want to generate a static pairlist now? Yes
? 💨 Do you want to download candle data now? Yes
? 💨 Do you want to hyperopt now? No
? 💨 Do you want to backtest now? No
? 💨 Do you want to start trading? No
[INFO] - : 💨 💨 💨
[INFO] - : 👉 Install MoniGoMani
[INFO] - : 💨 💨 💨
🤷 No "mgm-config.json" file found.
[WARNING] - : 🤷 No "mgm-config.json" file found.
✔ 👉  Clone MoniGoMani repository
😕 MoniGoMani installation failed


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  🎉  You are all set! We hope you enjoy your ride.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Rikj000** [comment] 2021-08-25 23:37
> 😕 MoniGoMani installation failed

@nuaimat could you re-try on the latest commit I pushed on a clean install?
It might not be a fix, but at least it should give us more info about the error that's occuring on your end.

**Comment by topscoder** [comment] 2021-08-26 13:54
Tested on clean Ubuntu install. Findings:

1. For each requirement which is unavailable the script stops. Have to install all of them one by one.
2. `/dev/fd/63: 216: [: 0: unexpected operator` -- Installer didn't die though.

And in the end some warnings/errors appeared:

```shell
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.9-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/root/freqtrade-mgm/.env/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Could not create virtual environment. Leaving now
expect: spawn id exp4 not open
    while executing
"expect "*Do you want to install plotting dependencies (plotly)*" { send -- "y\r" }"
    (file "/root/freqtrade-mgm/setup.exp" line 18)
    ```

**Comment by nuaimat** [comment] 2021-08-28 00:45
I tried with the latest revision of installer.sh 

<details>
<summary>Didn't work either</summary>
<p>

```
# ./installer.sh

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ⛱️  Welcome aboard! Let's get started ...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  🚦  Requirements check
  ======================

  ✅  Python3 is installed.
  ✅  Pip3 is installed.
  ✅  Git is installed.
  ✅  cURL is installed.
  ✅  Expect is installed.
  ✅  TA-Lib (C dependency package) is installed.

  👉  Are you ready to proceed? (y/n)

  y


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ⚙️  Downloading required files...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cloning into '/root/mgm/freqtrade-mgm/monigomani'...
remote: Enumerating objects: 4405, done.
remote: Counting objects: 100% (763/763), done.
remote: Compressing objects: 100% (488/488), done.
remote: Total 4405 (delta 512), reused 470 (delta 270), pack-reused 3642
Receiving objects: 100% (4405/4405), 264.02 MiB | 16.15 MiB/s, done.
Resolving deltas: 100% (2929/2929), done.
Branch 'development' set up to track remote branch 'development' from 'origin'.
Switched to a new branch 'development'

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ⚙️  Installing dependency packages...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Collecting art==5.2
  Downloading art-5.2-py2.py3-none-any.whl (571 kB)
     |████████████████████████████████| 571 kB 5.1 MB/s
Collecting cffi==1.14.6
  Downloading cffi-1.14.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (206 kB)
     |████████████████████████████████| 206 kB 13.6 MB/s
Collecting coloredlogs==15.0.1
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 1.5 MB/s
Collecting fire==0.4.0
  Downloading fire-0.4.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 1.8 MB/s
Collecting gitdb==4.0.7
  Downloading gitdb-4.0.7-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 863 kB/s
Collecting humanfriendly==9.2
  Downloading humanfriendly-9.2-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 2.5 MB/s
Collecting inquirerpy==0.2.4
  Downloading InquirerPy-0.2.4-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 2.6 MB/s
Collecting logger==1.4
  Downloading logger-1.4.tar.gz (1.2 kB)
Collecting plotly==5.2.2
  Downloading plotly-5.2.2-py2.py3-none-any.whl (21.8 MB)
     |████████████████████████████████| 21.8 MB 63 kB/s
Collecting prompt-toolkit==3.0.20
  Downloading prompt_toolkit-3.0.20-py3-none-any.whl (370 kB)
     |████████████████████████████████| 370 kB 12.6 MB/s
Requirement already satisfied: pycparser==2.20 in /usr/local/lib/python3.7/dist-packages (from -r ./monigomani/requirements-mgm.txt (line 19)) (2.20)
Requirement already satisfied: pygit2==1.6.1 in /usr/local/lib/python3.7/dist-packages (from -r ./monigomani/requirements-mgm.txt (line 20)) (1.6.1)
Requirement already satisfied: pyyaml==5.4.1 in /usr/local/lib/python3.7/dist-packages (from -r ./monigomani/requirements-mgm.txt (line 21)) (5.4.1)
Collecting shell-command==0.1
  Downloading shell_command-0.1.tar.gz (3.4 kB)
Collecting six==1.16.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting smmap==4.0.0
  Downloading smmap-4.0.0-py2.py3-none-any.whl (24 kB)
Collecting tenacity==8.0.1
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting termcolor==1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting wcwidth==0.2.5
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting yaspin==2.1.0
  Downloading yaspin-2.1.0-py3-none-any.whl (18 kB)
Requirement already satisfied: cached-property in /usr/local/lib/python3.7/dist-packages (from pygit2==1.6.1->-r ./monigomani/requirements-mgm.txt (line 20)) (1.5.2)
Using legacy 'setup.py install' for fire, since package 'wheel' is not installed.
Using legacy 'setup.py install' for logger, since package 'wheel' is not installed.
Using legacy 'setup.py install' for shell-command, since package 'wheel' is not installed.
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Installing collected packages: wcwidth, termcolor, tenacity, smmap, six, prompt-toolkit, humanfriendly, cffi, yaspin, shell-command, plotly, logger, inquirerpy, gitdb, fire, coloredlogs, art
    Running setup.py install for termcolor ... done
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: cffi
    Found existing installation: cffi 1.14.5
    Uninstalling cffi-1.14.5:
      Successfully uninstalled cffi-1.14.5
    Running setup.py install for shell-command ... done
    Running setup.py install for logger ... done
    Running setup.py install for fire ... done
Successfully installed art-5.2 cffi-1.14.6 coloredlogs-15.0.1 fire-0.4.0 gitdb-4.0.7 humanfriendly-9.2 inquirerpy-0.2.4 logger-1.4 plotly-5.2.2 prompt-toolkit-3.0.20 shell-command-0.1 six-1.16.0 smmap-4.0.0 tenacity-8.0.1 termcolor-1.1.0 wcwidth-0.2.5 yaspin-2.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
                                     _
 _ __ ___    __ _  _ __ ___         | |__   _   _  _ __  _ __  _   _
| '_ ` _ \  / _` || '_ ` _ \  _____ | '_ \ | | | || '__|| '__|| | | |
| | | | | || (_| || | | | | ||_____|| | | || |_| || |   | |   | |_| |
|_| |_| |_| \__, ||_| |_| |_|       |_| |_| \__,_||_|   |_|    \__, |
            |___/                                              |___/

[WARNING] - : Could not find .hurry config file at /root/mgm/freqtrade-mgm/.hurry
[INFO] - : 🍺 Configuration data written to ".hurry" file
[WARNING] - : FreqtradeCli - installation_exists() failed. Freqtrade binary not found in /root/mgm/freqtrade-mgm/.env/bin/freqtrade.
[WARNING] - : 🤷 No Freqtrade installation found.
? 💨 Do you want to install Freqtrade? Yes
? 💨 Do you want to install MoniGoMani? Yes
? 💨 Do you want to configure it now? Yes
? 💨 Do you want to generate a static pairlist now? Yes
? 💨 Do you want to download candle data now? Yes
? 💨 Do you want to hyperopt now? No
? 💨 Do you want to backtest now? No
? 💨 Do you want to start trading? No
[INFO] - : 💨 💨 💨
[INFO] - : 👉 Install Freqtrade
[INFO] - : 💨 💨 💨
[WARNING] - : FreqtradeCli - installation_exists() failed. Freqtrade binary not found in /root/mgm/freqtrade-mgm/.env/bin/freqtrade.
✔ 👉  Clone Freqtrade repository and resetting to commit 3503fdb4ec31be99f433fdce039543e0911964d6
Traceback (most recent call last):
  File "./monigomani/mgm-hurry", line 855, in <module>
    fire.Fire(MGMHurry)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./monigomani/mgm-hurry", line 136, in up
    self.install_freqtrade()
  File "./monigomani/mgm-hurry", line 217, in install_freqtrade
    self.freqtrade_cli.download_setup_freqtrade(target_dir, branch, commit)
  File "/root/mgm/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 172, in download_setup_freqtrade
    self.copy_installation_files(temp_dirname, target_dir)
  File "/root/mgm/freqtrade-mgm/monigomani/user_data/mgm_tools/mgm_hurry/FreqtradeCli.py", line 199, in copy_installation_files
    copytree(temp_dirname, target_dir, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  🎉  You are all set! We hope you enjoy your ride.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</p>
</details>

**Comment by BernhardHH** [comment] 2021-08-30 22:45
> I tried with the latest revision of installer.sh
> 
> Didn't work either

-> I bet your python3 version is 3.7 or below.

https://stackoverflow.com/questions/63661976/problems-using-shutil-copytree-in-python

(my python3 on Raspbian 10 is also 3.7, installer is no longer working for me)

**Comment by Rikj000** [comment] 2021-08-31 18:29
> https://stackoverflow.com/questions/63661976/problems-using-shutil-copytree-in-python/63662069#63662069

Indeed nice catch @topscoder :mechanical_arm: 
Seems like MGM will require **Python +3.8** going forward.

**Comment by Rikj000** [comment] 2021-09-02 22:30
Fixed with commit: https://github.com/Rikj000/MoniGoMani/commit/485f2e06d6879875804c0c9a8889716e1852cb30 (Tested on Ubuntu - WSL - Python3.8)

**Closed by Rikj000** 2021-09-02 22:30 UTC
Labels: Bug - Fix Needed, In Progress
